services:
  - type: web
    name: interview-bot
    runtime: node
    buildCommand: npm install && npm run build && npx prisma generate && npx prisma migrate deploy
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: interview-db
          property: connectionString

databases:
  - name: interview-db
    databaseName: interview_db
    user: interview_user
    plan: free